title: Rithas K
description: my small place in internet where i share my thoughts
base_url: https://rithask.me
permalink: /:title/
markdown: kramdown
exclude: ["Makefile", "README.md"]
image: card.jpg
twitter: "@rithaask"
github: "rithaask"
mail: "&#114;&#105;&#116;&#104;&#97;&#115;&#107;&#43;&#115;&#105;&#116;&#101;&#64;&#114;&#105;&#116;&#104;&#97;&#115;&#107;&#46;&#109;&#101;"
plugins:
  - jekyll-dotenv
